tabPanel("PBG",
         img(src = "lid.jpeg", align="right"),
         h3("Bienvenido a la pagina de estadisticas del Laboratorio de Ideas en Desarrollo"),
         p("En esta pagina usted podra explorar distintos aspectos relacionados al Producto Bruto Geografico de las Provincias Argentinas"),
         p("Usted podrá hacer comparaciones entre provincias para un dado momento de tiempo y a través del tiempo"),
         p("Mas explicaciones"),
         tabsetPanel(
           tabPanel("Composición",
                    sidebarLayout(
                      sidebarPanel(
                        selectInput("year", 
                                    label = "Escoja un Año",
                                    choices = list("2000"=2000,
                                                   "2001"=2001,
                                                   "2002"=2002,
                                                   "2003"=2003,
                                                   "2004"=2004,
                                                   "2005"=2005,
                                                   "2006"=2006,
                                                   "2007"=2007,
                                                   "2008"=2008,
                                                   "2009"=2009,
                                                   "2010"=2010,
                                                   "2011"=2011,
                                                   "2012"=2012,
                                                   "2013"=2013,
                                                   "2014"=2014),
                                    selected = 2000
                        ),
                        selectInput("provincia", 
                                    label = "Elija una Provincia",
                                    choices = list("Ciudad Autónoma de Buenos Aires"="AR-C",
                                                   "Buenos Aires"="AR-B",
                                                   "Catamarca"="AR-K",
                                                   "Cordoba"="AR-X",
                                                   "Corrientes"="AR-W",
                                                   "Chaco"="AR-H",
                                                   "Chubut"="AR-U",
                                                   "Entre Rios"="AR-E",
                                                   "Formosa"="AR-P",
                                                   "Jujuy"="AR-Y",
                                                   "La Pampa"="AR-L",
                                                   "La Rioja"="AR-F",
                                                   "Mendoza"="AR-M",
                                                   "Misiones"="AR-N",
                                                   "Neuquen"="AR-Q",
                                                   "Rio Negro"="AR-R",
                                                   "Salta"="AR-A",
                                                   "San Juan"="AR-J",
                                                   "San Luis"="AR-D",
                                                   "Santa Cruz"="AR-Z",
                                                   "Santa Fe"="AR-S",
                                                   "Santiago del Estero"="AR-G",
                                                   "Tucuman"="AR-T",
                                                   "Tierra del Fuego"="AR-V",
                                                   "Malvinas"="FK"),
                                    selected = "AR-B"
                        )
                      ),
                      mainPanel(list(h4("Composicion del Producto Bruto Geografico"), p("En estos graficos de torta usted puede observar la composición del PBG de la provincia seleccionada para el año seleccionado ")), htmlOutput("piechart"), p("Nota: Si no se produce un grafico es porque no hay datos disponibles"))
                    )
           ),
           tabPanel("Evolución",
                    sidebarLayout(
                      sidebarPanel(
                        selectInput("provincia2", 
                                    label = "Elija una Provincia",
                                    choices = list("Ciudad Autónoma de Buenos Aires"="AR-C",
                                                   "Buenos Aires"="AR-B",
                                                   "Catamarca"="AR-K",
                                                   "Cordoba"="AR-X",
                                                   "Corrientes"="AR-W",
                                                   "Chaco"="AR-H",
                                                   "Chubut"="AR-U",
                                                   "Entre Rios"="AR-E",
                                                   "Formosa"="AR-P",
                                                   "Jujuy"="AR-Y",
                                                   "La Pampa"="AR-L",
                                                   "La Rioja"="AR-F",
                                                   "Mendoza"="AR-M",
                                                   "Misiones"="AR-N",
                                                   "Neuquen"="AR-Q",
                                                   "Rio Negro"="AR-R",
                                                   "Salta"="AR-A",
                                                   "San Juan"="AR-J",
                                                   "San Luis"="AR-D",
                                                   "Santa Cruz"="AR-Z",
                                                   "Santa Fe"="AR-S",
                                                   "Santiago del Estero"="AR-G",
                                                   "Tucuman"="AR-T",
                                                   "Tierra del Fuego"="AR-V",
                                                   "Malvinas"="FK"),
                                    selected = "AR-B"
                        ),
                        checkboxGroupInput(inputId="variable2", 
                                           label = "Escoja una Variable",
                                           choices = list("PBG a precios de mercado"="PBG.a.precios.de.mercado..aproximados..",
                                                          "PBG a precios de productor"="PBG.a.precios.de.productor.",
                                                          "Agricultura ganadería caza y silvicultura"="A..Agricultura..ganadería..caza.y.silvicultura",
                                                          "Pesca y servicios conexos"="Pesca.y.servicios.conexos",
                                                          "Explotación de minas y canteras"="Explotación.de.minas.y.canteras",
                                                          "Industria Manufacturera"="Industria.Manufacturera",
                                                          "Electricidad gas y agua"="Electricidad..gas.y.agua",
                                                          "Construcción",
                                                          "Sectores productores de servicios"="Sectores.productores.de.servicios",
                                                          "Comercio al por mayor al por menor y reparaciones"="Comercio.al.por.mayor..al.por.menor.y.reparaciones",
                                                          "Servicios de hotelería y restaurantes"="Servicios.de.hotelería.y.restaurantes",
                                                          "Servicio de transporte de almacenamiento y de comunicaciones" ="Servicio.de.transporte..de.almacenamiento.y.de.comunicaciones",
                                                          "Intermediación financiera y otros servicios financieros"="Intermediación.financiera.y.otros.servicios.financieros",
                                                          "Servicios inmobiliarios empresariales y de alquiler"="Servicios.inmobiliarios..empresariales.y.de.alquiler",
                                                          "Administración pública defensa y seguridad social obligatoria"="Administración.pública..defensa.y.seguridad.social.obligatoria",
                                                          "Enseñanza",                                                     
                                                          "Servicios sociales y de salud"="Servicios.sociales.y.de.salud",
                                                          "Servicios comunitarios sociales y personales"="Servicios.comunitarios..sociales.y.personales.n.c.p.",
                                                          "Servicios de hogares privados que contratan servicio doméstico"="Servicios.de.hogares.privados.que.contratan.servicio.doméstico"),
                                           selected = "PBG.a.precios.de.mercado..aproximados.."
                        )
                      ),
                      mainPanel(list(h4("Composicion del Producto Bruto Geografico"), p("En estos graficos usted puede observar la evolución del PBG y sus componentes ")), htmlOutput("linechart"), p("Nota: Si no se produce un grafico es porque no hay datos disponibles"))
                    )
           ),
           tabPanel("Comparación",
                    sidebarLayout(
                      sidebarPanel(
                        selectInput("variable3", 
                                    label = "Escoja una Variable",
                                    choices = list("PBG a precios de mercado"="PBG.a.precios.de.mercado..aproximados..",
                                                   "PBG a precios de productor"="PBG.a.precios.de.productor.",
                                                   "Agricultura ganadería caza y silvicultura"="A..Agricultura..ganadería..caza.y.silvicultura",
                                                   "Pesca y servicios conexos"="Pesca.y.servicios.conexos",
                                                   "Explotación de minas y canteras"="Explotación.de.minas.y.canteras",
                                                   "Industria Manufacturera"="Industria.Manufacturera",
                                                   "Electricidad gas y agua"="Electricidad..gas.y.agua",
                                                   "Construcción",
                                                   "Sectores productores de servicios"="Sectores.productores.de.servicios",
                                                   "Comercio al por mayor al por menor y reparaciones"="Comercio.al.por.mayor..al.por.menor.y.reparaciones",
                                                   "Servicios de hotelería y restaurantes"="Servicios.de.hotelería.y.restaurantes",
                                                   "Servicio de transporte de almacenamiento y de comunicaciones" ="Servicio.de.transporte..de.almacenamiento.y.de.comunicaciones",
                                                   "Intermediación financiera y otros servicios financieros"="Intermediación.financiera.y.otros.servicios.financieros",
                                                   "Servicios inmobiliarios empresariales y de alquiler"="Servicios.inmobiliarios..empresariales.y.de.alquiler",
                                                   "Administración pública defensa y seguridad social obligatoria"="Administración.pública..defensa.y.seguridad.social.obligatoria",
                                                   "Enseñanza",                                                     
                                                   "Servicios sociales y de salud"="Servicios.sociales.y.de.salud",
                                                   "Servicios comunitarios sociales y personales"="Servicios.comunitarios..sociales.y.personales.n.c.p.",
                                                   "Servicios de hogares privados que contratan servicio doméstico"="Servicios.de.hogares.privados.que.contratan.servicio.doméstico"),
                                    selected = "PBG.a.precios.de.mercado..aproximados.."
                        ),
                        checkboxGroupInput("provincia3", 
                                           label = "Elija una Provincia",
                                           choices = list("Ciudad Autónoma de Buenos Aires"="Ciudad.Aurtónoma.de.Buenos.Aires.",
                                                          "Buenos Aires"="Buenos.Aires.",
                                                          "Catamarca",
                                                          "Cordoba",
                                                          "Corrientes",
                                                          "Chaco",
                                                          "Chubut",
                                                          "Entre Rios"="Entre.Ríos",
                                                          "Formosa",
                                                          "Jujuy",
                                                          "La Pampa"="La.Pampa",
                                                          "La Rioja"="La.Rioja",
                                                          "Mendoza",
                                                          "Misiones",
                                                          "Neuquen",
                                                          "Rio Negro"="Río.Negro",
                                                          "Salta",
                                                          "San Juan"="San.Juan.",
                                                          "San Luis"="San.Luis",
                                                          "Santa Cruz"="Santa.Cruz",
                                                          "Santa Fe"= "Santa.Fe",
                                                          "Santiago del Estero"="Santiago.del.Estero",
                                                          "Tucuman"="Tucumán",
                                                          "Tierra del Fuego"="Tierra.del.Fuego",
                                                          "Malvinas"="FK"),
                                           selected = "Chubut"
                        )
                      ),
                      mainPanel(list(h4("Composicion del Producto Bruto Geografico"), p("En estos graficos usted puede comparar la evolución del PBG y sus componentes por provincia ")), htmlOutput("linechartcomp"), p("Nota: Si no se produce un grafico es porque no hay datos disponibles"))
                    )
           ),
           tabPanel("Mapas",
                    sidebarLayout(
                      sidebarPanel(
                        selectInput("year_map", 
                                    label = "Escoja un Año",
                                    choices = list("2000"=2000,
                                                   "2001"=2001,
                                                   "2002"=2002,
                                                   "2003"=2003,
                                                   "2004"=2004,
                                                   "2005"=2005,
                                                   "2006"=2006,
                                                   "2007"=2007,
                                                   "2008"=2008,
                                                   "2009"=2009,
                                                   "2010"=2010,
                                                   "2011"=2011,
                                                   "2012"=2012,
                                                   "2013"=2013,
                                                   "2014"=2014),
                                    selected = 2000
                        ),
                        selectInput("variable_map", 
                                    label = "Escoja una Variable",
                                    choices = list("PBG a precios de mercado"="PBG.a.precios.de.mercado..aproximados..",
                                                   "PBG a precios de productor"="PBG.a.precios.de.productor.",
                                                   "Agricultura ganadería caza y silvicultura"="A..Agricultura..ganadería..caza.y.silvicultura",
                                                   "Pesca y servicios conexos"="Pesca.y.servicios.conexos",
                                                   "Explotación de minas y canteras"="Explotación.de.minas.y.canteras",
                                                   "Industria Manufacturera"="Industria.Manufacturera",
                                                   "Electricidad gas y agua"="Electricidad..gas.y.agua",
                                                   "Construcción",
                                                   "Sectores productores de servicios"="Sectores.productores.de.servicios",
                                                   "Comercio al por mayor al por menor y reparaciones"="Comercio.al.por.mayor..al.por.menor.y.reparaciones",
                                                   "Servicios de hotelería y restaurantes"="Servicios.de.hotelería.y.restaurantes",
                                                   "Servicio de transporte de almacenamiento y de comunicaciones" ="Servicio.de.transporte..de.almacenamiento.y.de.comunicaciones",
                                                   "Intermediación financiera y otros servicios financieros"="Intermediación.financiera.y.otros.servicios.financieros",
                                                   "Servicios inmobiliarios empresariales y de alquiler"="Servicios.inmobiliarios..empresariales.y.de.alquiler",
                                                   "Administración pública defensa y seguridad social obligatoria"="Administración.pública..defensa.y.seguridad.social.obligatoria",
                                                   "Enseñanza",                                                     
                                                   "Servicios sociales y de salud"="Servicios.sociales.y.de.salud",
                                                   "Servicios comunitarios sociales y personales"="Servicios.comunitarios..sociales.y.personales.n.c.p.",
                                                   "Servicios de hogares privados que contratan servicio doméstico"="Servicios.de.hogares.privados.que.contratan.servicio.doméstico"),
                                    selected = "PBG.a.precios.de.mercado..aproximados..")
                      ),
                      mainPanel(htmlOutput("mapa"))
                    )
           )
         )
)