require(shiny)

shinyUI(fluidPage(theme = "bootstrap.css",
  titlePanel(list(tags$div(class="h1", 
             list(tags$a(href="http://lid.maimonides.edu", "Laboratorio de Ideas en Desarrollo"),
             tags$br(),
             tags$a(href="http://www.maimonides.edu/es/", "Universidad Maimónides")
             )))
  ),
  sidebarPanel(
    conditionalPanel(condition="input.conditionedPanels==1",
                     selectInput("year", 
                                 label = "Escoja un Año",
                                 choices = list("2000"=2000,
                                                "2001"=2001,
                                                "2002"=2002,
                                                "2003"=2003,
                                                "2004"=2004,
                                                "2005"=2005,
                                                "2006"=2006,
                                                "2007"=2007,
                                                "2008"=2008,
                                                "2009"=2009,
                                                "2010"=2010,
                                                "2011"=2011,
                                                "2012"=2012,
                                                "2013"=2013,
                                                "2014"=2014),
                                 selected = 2000),
                     selectInput("variable", 
                                 label = "Escoja una Variable",
                                 choices = list("PBG a precios de mercado"="PBG.a.precios.de.mercado..aproximados..",
                                                "PBG a precios de productor"="PBG.a.precios.de.productor.",
                                                "Agricultura ganadería caza y silvicultura"="A..Agricultura..ganadería..caza.y.silvicultura",
                                                "Pesca y servicios conexos"="Pesca.y.servicios.conexos",
                                                "Explotación de minas y canteras"="Explotación.de.minas.y.canteras",
                                                "Industria Manufacturera"="Industria.Manufacturera",
                                                "Electricidad gas y agua"="Electricidad..gas.y.agua",
                                                "Construcción",
                                                "Sectores productores de servicios"="Sectores.productores.de.servicios",
                                                "Comercio al por mayor al por menor y reparaciones"="Comercio.al.por.mayor..al.por.menor.y.reparaciones",
                                                "Servicios de hotelería y restaurantes"="Servicios.de.hotelería.y.restaurantes",
                                                "Servicio de transporte de almacenamiento y de comunicaciones" ="Servicio.de.transporte..de.almacenamiento.y.de.comunicaciones",
                                                "Intermediación financiera y otros servicios financieros"="Intermediación.financiera.y.otros.servicios.financieros",
                                                "Servicios inmobiliarios empresariales y de alquiler"="Servicios.inmobiliarios..empresariales.y.de.alquiler",
                                                "Administración pública defensa y seguridad social obligatoria"="Administración.pública..defensa.y.seguridad.social.obligatoria",
                                                "Enseñanza",                                                     
                                                "Servicios sociales y de salud"="Servicios.sociales.y.de.salud",
                                                "Servicios comunitarios sociales y personales"="Servicios.comunitarios..sociales.y.personales.n.c.p.",
                                                "Servicios de hogares privados que contratan servicio doméstico"="Servicios.de.hogares.privados.que.contratan.servicio.doméstico"),
                                 selected = "PBG.a.precios.de.mercado..aproximados..")
                     
    ),
    conditionalPanel(condition="input.conditionedPanels==2",
                     selectInput("year2", 
                                 label = "Escoja un Año",
                                 choices = list("2000"=2000,
                                                "2001"=2001,
                                                "2002"=2002,
                                                "2003"=2003,
                                                "2004"=2004,
                                                "2005"=2005,
                                                "2006"=2006,
                                                "2007"=2007,
                                                "2008"=2008,
                                                "2009"=2009,
                                                "2010"=2010,
                                                "2011"=2011,
                                                "2012"=2012,
                                                "2013"=2013,
                                                "2014"=2014),
                                 selected = 2000),
                     selectInput("variable2", 
                                 label = "Escoja una Variable",
                                 choices = list("Empresas Total"="Empresas.Total",
                                                "Agricultura, ganadería y pesca"="Agricultura..ganadería.y.pesca",
                                                "Minería y petroleo"="Minería.y.petroleo",
                                                "Industria",
                                                "Comercio",
                                                "Servicios",                     
                                                "Electricidad, gas y agua"="Electricidad..gas.y.agua",
                                                "Construcción" ),
                                 selected = "Industria")

    ),
    conditionalPanel(condition="input.conditionedPanels==3",
                     selectInput("year3", 
                                 label = "Escoja un Año",
                                 choices = list("2000"=2000,
                                                "2001"=2001,
                                                "2002"=2002,
                                                "2003"=2003,
                                                "2004"=2004,
                                                "2005"=2005,
                                                "2006"=2006,
                                                "2007"=2007,
                                                "2008"=2008,
                                                "2009"=2009,
                                                "2010"=2010,
                                                "2011"=2011,
                                                "2012"=2012,
                                                "2013"=2013,
                                                "2014"=2014),
                                 selected = 2000),
                     selectInput("variable3", 
                                 label = "Escoja una Variable",
                                 choices = list("Empleo Formal Total"="Empleo.Formal.Total",
                                                "Agricultura, ganadería y pesca"="Agricultura..ganadería.y.pesca",
                                                "Minería y petroleo"="Minería.y.petroleo",
                                                "Industria",
                                                "Comercio",
                                                "Servicios",                     
                                                "Electricidad, gas y agua"="Electricidad..gas.y.agua",
                                                "Construcción" ),
                                 selected = "Industria")
    )
                     
  ),
  
  mainPanel(
    p("Bienvenido a la pagina de datos sobre produccion por provincias de la argentina"),
    tabsetPanel(
      tabPanel("Home", div(id="link",tags$a("Evolucion")), value=0 ),
      tabPanel("PBG", list(h4("Producto Bruto Geografico"), p("Necesita una explicación acá")), htmlOutput("mapa"), value=1),
      tabPanel("Empresas", list(h4("Empresas por Sector"), p("Necesita una explicación acá")), htmlOutput("mapaxsector"), value=2),
      tabPanel("Empleo",list(h4("Empleo por Sector"), p("Necesita una explicación acá")), htmlOutput("mapaxempleo"), value=3),	
      id="conditionedPanels"
    )
)
))
